fta_sport/articles/urls.py
from django.conf.urls import url, include
from . import views as articles_views
from django.views.generic import TemplateView

app_name = 'articles'

urlpatterns = [
    url(r'^(?P<slug>[-_\w]+)/$', articles_views.DetailView.as_view(), name='article-detail'),
    url(r'^', articles_views.IndexView.as_view(), name='index'),
]

fta_sport/fta_sport/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^news/', include('articles.urls')),
    url(r'^home/', include('sports.urls')),
    url(r'^cricket-view/', include('cricket.urls')),
    url(r'^monthly-view/', include('monthly_view.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fta_sport/monthly_view/urls.py
from django.conf.urls import url, include
from . import views as monthly_view
from django.views.generic import TemplateView

app_name = 'monthly_view'

urlpatterns = [
    url(r'^monthly-view/$', monthly_view.CricketCalendar.as_view(), name='cricket-monthly'),
]

fta_sport/rugby/urls.py
from django.conf.urls import url, include
from . import views as rugby_views
from django.views.generic import TemplateView

app_name = 'rugby'

urlpatterns = [

]

fta_sport/sports/urls.py
from django.conf.urls import url, include
from . import views as sports_views
from monthly_view import views as monthly_view
from django.views.generic import TemplateView

app_name = 'sports'

urlpatterns = [
    url(r'^(?P<sport_slug>[-_\w]+)/$', sports_views.SportListView.as_view(), name='sport-home'),
    #url(r'^monthly-view/$', monthly_view.IndexView.as_view(), name='monthly-index'),
    url(r'^(?P<category_slug>[-_\w]+)/$', sports_views.ListView.as_view(), name='sport-category'),
    url(r'^$', sports_views.IndexView.as_view(), name='index'),
]

fta_sport/sports/models.py
from django.db import models
from django_countries.fields import CountryField

# Create your models here.

class Sport_Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    category_slug = models.SlugField(max_length=100, db_index=True)

    def __unicode__(self):
        return '%s' % self.name

    def __str__(self):
       return  self.name

   #def get_absolute_url(self):
       #return reverse('sports:sport-category', kwargs={'slug':self.category_slug})

class Sport(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    sport_slug = models.SlugField(max_length=100, db_index=True)
    category = models.ForeignKey('Sport_Category', on_delete=models.CASCADE,)

    def __unicode__(self):
        return '%s' % self.name

    def __str__(self):
        return self.name
       #return 'Category: ' + self.name

    #def list_of_sports_in_category(self):
        #sport_cat = self.category.name
        #return sport_cat

    def get_absolute_url(self):
        return reverse('sports:sport-home', kwargs={'slug':self.sport_slug})

class Gender(models.Model):
    gender = models.CharField(max_length=50) #male/female

    def __str__(self):
       return self.gender

class Tier(models.Model):
    tier_level = models.CharField(max_length=50)

    def __str__(self):
       return self.tier_level

class MatchType(models.Model):
    name = models.CharField(max_length=250)
    tier = models.ForeignKey('Tier', on_delete=models.CASCADE)
    sport = models.ForeignKey('Sport', on_delete=models.CASCADE)

    def __str__(self):
       return '%s %s' % (self.sport, self.name)

class Team(models.Model):
    sport = models.ForeignKey('Sport', on_delete=models.CASCADE)
    country = CountryField()
    team_name = models.CharField(max_length=250)
    gender = models.ForeignKey('Gender', on_delete=models.CASCADE)
    tier = models.ForeignKey('Tier', on_delete=models.CASCADE)

    def __str__(self):
       return self.team_name

fta_sport/sports/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.core.urlresolvers import reverse, reverse_lazy
from django.views import generic
#my stuff
from sports.models import Sport_Category, Sport
from articles.models import Post
import datetime

class IndexView(generic.ListView):
	template_name="sports/index.html"
	context_object_name='all_sport_category'

	def get_queryset(self):
		return Sport_Category.objects.all()

#unused in templates
class ListView(generic.ListView):
	template_name="sports/sport-category.html"
	context_object_name='category_list'

	def get_queryset(self):
		return Sport_Category.objects.all()

class SportListView(generic.ListView):
	template_name="sports/sport-home.html"
	context_object_name='sport_list'

	def get_queryset(self):
		self.sport = get_object_or_404(Sport, sport_slug=self.kwargs['sport_slug'])
		return Post.objects.filter(post_category=self.sport)
	##with this we are filtering the sports by the posts, instead we need to filter the posts by sport.

fta_sport/sports/templates/sports/index.html
{% include "base.html" %}

Sports Index!

{% block content %}
{% for sport_category in all_sport_category %}
  <li>{{ sport_category.name }} </li>
  {% for sports in sport_category.sport_set.all %}
    <li>{{ sports.name }}</li>
  {% endfor %}
{% endfor %}

{% for posts in all_sport_category %}
 {{ post.title }}
{% endfor %}

{% endblock %}

fta_sport/sports/templates/sports/sport-category.html
sport-category 

fta_sport/sports/templates/sports/sport-home.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="carousel slide col-6" id="carouselExampleIndicators"  data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="5"></li>
        </ol>

        <div class="carousel-inner" role="listbox">

          {% for post in sport_list|slice:":5"%}
          <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}" id="slide{{ forloop.counter }}">
            <a href="{% url 'articles:article-detail' post.post_slug %}">
            <img class="d-block img-fluid" src="{{ post.headline_image.url }}" alt="First slide">
            <div class="carousel-caption d-none d-md-block">
              <h3>{{ post.title }}</h3>
              <p>{{ post.short_description }}</p>
            </div>
            </a>
          </div>
          {% endfor %}


        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
        </div>
      </div>

      <div class="top-headline offset-2 col-4">
        <div class="top-title d-flex justify-content-center"><h3 class="gold-text">Top Headlines</h3></div>
        {{post.tile}}
        <a href="{% url 'monthly_view:cricket-monthly' %}">Calender</a>
      </div>
    </div>


    <div class="row">
      {% for post in sport_list|slice:"5:" %}

      <div class="card article-card ml-3 mt-5" style="width: 20rem;">
        <a href="{% url 'articles:article-detail' post.post_slug %}">
          <img class="card-img-top" src="{{ post.headline_image.url }}" alt="Card image cap">
        </a>
          <div class="card-body">
            <a href="{% url 'articles:article-detail' post.post_slug %}">
              <h4 class="card-title">{{ post.title }}</h4>
            </a>
            <p class="card-text">{{ post.short_description }}</p>
          </div>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}