fta_sport/fta_sport/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^news/', include('articles.urls')),
    url(r'^home/', include('sports.urls')),
    url(r'^cricket-view/', include('cricket.urls')),
    url(r'^monthly-view/', include('monthly_view.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fta_sport/rugby/urls.py
from django.conf.urls import url, include
from . import views as rugby_views
from django.views.generic import TemplateView

app_name = 'rugby'

urlpatterns = [

]

fta_sport/sports/urls.py
from django.conf.urls import url, include
from . import views as sports_views
from monthly_view import views as monthly_view
from django.views.generic import TemplateView

app_name = 'sports'

urlpatterns = [
    url(r'^(?P<sport_slug>[-_\w]+)/$', sports_views.SportListView.as_view(), name='sport-home'),
    #url(r'^monthly-view/$', monthly_view.IndexView.as_view(), name='monthly-index'),
    url(r'^(?P<category_slug>[-_\w]+)/$', sports_views.ListView.as_view(), name='sport-category'),
    url(r'^$', sports_views.IndexView.as_view(), name='index'),
]

fta_sport/sports/models.py
from django.db import models
from django_countries.fields import CountryField

# Create your models here.

class Sport_Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    category_slug = models.SlugField(max_length=100, db_index=True)

    def __unicode__(self):
        return '%s' % self.name

    def __str__(self):
       return  self.name

   #def get_absolute_url(self):
       #return reverse('sports:sport-category', kwargs={'slug':self.category_slug})

class Sport(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    sport_slug = models.SlugField(max_length=100, db_index=True)
    category = models.ForeignKey('Sport_Category', on_delete=models.CASCADE,)

    def __unicode__(self):
        return '%s' % self.name

    def __str__(self):
        return self.name
       #return 'Category: ' + self.name

    #def list_of_sports_in_category(self):
        #sport_cat = self.category.name
        #return sport_cat

    def get_absolute_url(self):
        return reverse('sports:sport-home', kwargs={'slug':self.sport_slug})

class Gender(models.Model):
    gender = models.CharField(max_length=50) #male/female

    def __str__(self):
       return self.gender

class Tier(models.Model):
    tier_level = models.CharField(max_length=50)

    def __str__(self):
       return self.tier_level

class MatchType(models.Model):
    name = models.CharField(max_length=250)
    tier = models.ForeignKey('Tier', on_delete=models.CASCADE)
    sport = models.ForeignKey('Sport', on_delete=models.CASCADE)

    def __str__(self):
       return '%s %s' % (self.sport, self.name)

class Team(models.Model):
    sport = models.ForeignKey('Sport', on_delete=models.CASCADE)
    country = CountryField()
    team_name = models.CharField(max_length=250)
    gender = models.ForeignKey('Gender', on_delete=models.CASCADE)
    tier = models.ForeignKey('Tier', on_delete=models.CASCADE)

    def __str__(self):
       return self.team_name

fta_sport/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}FTA Sport{% endblock %}</title>
      {# Load the tag library #}
      {% load bootstrap4 %}
      {% load static %}

      {# Load CSS and JavaScript #}
      {% bootstrap_css %}
      {% bootstrap_javascript %}
      {% bootstrap_jquery %}
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

      {# Display django.contrib.messages as Bootstrap alerts #}
      {% bootstrap_messages %}
      <link rel="stylesheet" href="{% static 'css/main-style.css' %}">
      <link rel="stylesheet" href="{% static 'flags/sprite.css' %}">
      <link rel="stylesheet" href="{% static 'font-awesome/font-awesome-4.7.0/css/font-awesome.css' %}">
  </head>
  <body>

{% block main_menu %}
  {% include "main_menu.html" %}
{% endblock %}

{% block content %}

{% endblock %}
  </body>
</html>

fta_sport/templates/main_menu.html
{% extends "base.html" %}
{% block main_menu %}
<nav class="navbar navbar-expand-lg main-nav">
  <a class="navbar-brand" href="{% url 'sports:index' %}">FTA Sport</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% for sport_category in categories %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ sport_category.name }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% for sports in sport_category.sport_set.all %}
            <a href="{% url 'sports:sport-home' sports.sport_slug %}">{{ sports.name }}</a>
          {% endfor %}
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</nav>

{% endblock %}